"""update_embedding_dimension_to_200

Revision ID: 0374947aaeb9
Revises: f11e25f195a3
Create Date: 2026-04-20 07:06:15.343519

"""
from typing import Sequence, Union

from alembic import op

import pgvector
import sys
import asyncio

if sys.platform == "win32":
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

# revision identifiers, used by Alembic.
revision: str = '0374947aaeb9'
down_revision: Union[str, Sequence[str], None] = 'f11e25f195a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=200),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=False)
    # ### end Alembic commands ###
