"""Add event confidence and reasoning to notes

Revision ID: 03eac4a261fc
Revises: 40090a17e4dc
Create Date: 2026-04-19 07:02:23.776731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sys
import asyncio

if sys.platform == "win32":
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

# revision identifiers, used by Alembic.
revision: str = '03eac4a261fc'
down_revision: Union[str, Sequence[str], None] = '40090a17e4dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('event_confidence', sa.String(length=20), nullable=True))
    op.add_column('notes', sa.Column('event_reasoning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'event_reasoning')
    op.drop_column('notes', 'event_confidence')
    # ### end Alembic commands ###
