"""Rename occurrence_time to event_date and change type to string

Revision ID: 2cb921bd9094
Revises: 03eac4a261fc
Create Date: 2026-04-19 07:10:34.479141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sys
import asyncio

if sys.platform == "win32":
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

# revision identifiers, used by Alembic.
revision: str = '2cb921bd9094'
down_revision: Union[str, Sequence[str], None] = '03eac4a261fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('event_date', sa.String(length=100), nullable=True))
    op.drop_column('notes', 'occurrence_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('occurrence_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('notes', 'event_date')
    # ### end Alembic commands ###
