"""Add new collumns to note

Revision ID: 3e56041181ae
Revises: 2cb921bd9094
Create Date: 2026-04-19 13:05:52.718632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sys
import asyncio

if sys.platform == "win32":
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

# revision identifiers, used by Alembic.
revision: str = '3e56041181ae'
down_revision: Union[str, Sequence[str], None] = '2cb921bd9094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('event_start_date', sa.Date(), nullable=True))
    op.add_column('notes', sa.Column('event_end_date', sa.Date(), nullable=True))
    op.alter_column('notes', 'event_date',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using="NULLIF(event_date, '')::date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'event_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               postgresql_using="event_date::text")
    op.drop_column('notes', 'event_end_date')
    op.drop_column('notes', 'event_start_date')
    # ### end Alembic commands ###
