"""Add analysis fields to note

Revision ID: 48ae42e211c7
Revises: f0ac188a1acd
Create Date: 2026-04-18 08:27:49.360491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sys
import asyncio

if sys.platform == "win32":
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

# revision identifiers, used by Alembic.
revision: str = '48ae42e211c7'
down_revision: Union[str, Sequence[str], None] = 'f0ac188a1acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('notes', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('notes', sa.Column('sentiment', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'sentiment')
    op.drop_column('notes', 'tags')
    op.drop_column('notes', 'summary')
    # ### end Alembic commands ###
