"""Add updated_at field

Revision ID: f0ac188a1acd
Revises: 0310ac136f05
Create Date: 2026-04-18 07:11:21.486444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sys
import asyncio

if sys.platform == "win32":
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

# revision identifiers, used by Alembic.
revision: str = 'f0ac188a1acd'
down_revision: Union[str, Sequence[str], None] = '0310ac136f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns as nullable first
    op.add_column('notes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # Populate existing rows with created_at value
    op.execute("UPDATE notes SET updated_at = created_at")
    op.execute("UPDATE users SET updated_at = created_at")
    
    # Change to NOT NULL
    op.alter_column('notes', 'updated_at', nullable=False)
    op.alter_column('users', 'updated_at', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('notes', 'updated_at')
    # ### end Alembic commands ###
