"""Remove redundant date columns

Revision ID: f11e25f195a3
Revises: 3e56041181ae
Create Date: 2026-04-19 14:36:09.692165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sys
import asyncio

if sys.platform == "win32":
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

# revision identifiers, used by Alembic.
revision: str = 'f11e25f195a3'
down_revision: Union[str, Sequence[str], None] = '3e56041181ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_note_chunks_chunk_index', 'note_chunks', ['chunk_index'], unique=False)
    op.drop_column('notes', 'event_end_date')
    op.drop_column('notes', 'event_start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('event_start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('event_end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index('idx_note_chunks_chunk_index', table_name='note_chunks')
    # ### end Alembic commands ###
